# Generated by Django 3.1.2 on 2020-10-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimerNombre', models.CharField(max_length=50)),
                ('SegundoNombre', models.CharField(max_length=50)),
                ('PrimerApellido', models.CharField(max_length=50)),
                ('SegundoApellido', models.CharField(max_length=50)),
                ('Usuario', models.CharField(max_length=50)),
                ('Contraseña', models.CharField(max_length=50)),
                ('DocumentoId', models.IntegerField()),
                ('TipoDocumento', models.CharField(max_length=50)),
                ('Edad', models.IntegerField()),
                ('CorreoElectronico', models.CharField(max_length=90)),
                ('TipoUsuario', models.CharField(default='Usuario', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteAdministrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaReporte', models.DateField()),
                ('ModalidadCitaFrecuente', models.CharField(max_length=300)),
                ('MedicosAusentes', models.CharField(max_length=300)),
                ('PacientesDia', models.IntegerField()),
                ('NumCitasCanceladas', models.IntegerField()),
                ('NumCitasConfirmadasAuto', models.IntegerField()),
                ('NumCitasConfirmadasManal', models.IntegerField()),
            ],
        ),
    ]
