# Generated by Django 3.1.2 on 2020-10-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreC', models.CharField(max_length=20)),
                ('DepartamentoC', models.CharField(max_length=20)),
                ('Prueba', models.CharField(max_length=20)),
                ('Prueba2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreC', models.CharField(max_length=20)),
                ('DepartamentoC', models.CharField(max_length=20)),
                ('Pruebas', models.IntegerField()),
                ('Prueba2', models.CharField(max_length=20)),
            ],
        ),
    ]
