# Generated by Django 3.1.2 on 2020-10-24 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreC', models.CharField(max_length=70)),
                ('DepartamentoC', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HorarioLlegada', models.TimeField()),
                ('HoraioSalida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimerNombre', models.CharField(max_length=50)),
                ('SegundoNombre', models.CharField(max_length=50)),
                ('PrimerApellido', models.CharField(max_length=50)),
                ('SegundoApellido', models.CharField(max_length=50)),
                ('Usuario', models.CharField(max_length=50)),
                ('Contraseña', models.CharField(max_length=50)),
                ('DocumentoId', models.IntegerField()),
                ('TipoDocumento', models.CharField(max_length=50)),
                ('Edad', models.IntegerField()),
                ('CorreoElectronico', models.CharField(max_length=90)),
                ('TipoUsuario', models.CharField(default='Usuario', max_length=20)),
                ('EPSP', models.CharField(max_length=90)),
                ('Telefono', models.CharField(max_length=20)),
                ('Whatsapp', models.CharField(max_length=20)),
                ('Hipertension', models.BooleanField(default=0)),
                ('Diabetes', models.BooleanField(default=0)),
                ('Cardiacos', models.BooleanField(default=0)),
                ('Otros', models.CharField(default='', max_length=500)),
                ('Ciudad', models.CharField(default='', max_length=50)),
                ('Barrio', models.CharField(default='', max_length=50)),
                ('complemento', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteSecretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaReporte', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimerNombre', models.CharField(max_length=50)),
                ('SegundoNombre', models.CharField(max_length=50)),
                ('PrimerApellido', models.CharField(max_length=50)),
                ('SegundoApellido', models.CharField(max_length=50)),
                ('Usuario', models.CharField(max_length=50)),
                ('Contraseña', models.CharField(max_length=50)),
                ('DocumentoId', models.IntegerField()),
                ('TipoDocumento', models.CharField(max_length=50)),
                ('Edad', models.IntegerField()),
                ('CorreoElectronico', models.CharField(max_length=90)),
                ('TipoUsuario', models.CharField(default='Usuario', max_length=20)),
                ('Whatsapp', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimerNombre', models.CharField(max_length=50)),
                ('SegundoNombre', models.CharField(max_length=50)),
                ('PrimerApellido', models.CharField(max_length=50)),
                ('SegundoApellido', models.CharField(max_length=50)),
                ('Usuario', models.CharField(max_length=50)),
                ('Contraseña', models.CharField(max_length=50)),
                ('DocumentoId', models.IntegerField()),
                ('TipoDocumento', models.CharField(max_length=50)),
                ('Edad', models.IntegerField()),
                ('CorreoElectronico', models.CharField(max_length=90)),
                ('TipoUsuario', models.CharField(default='Usuario', max_length=20)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDeCitas.especialidad')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDeCitas.horario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModalidadCita', models.CharField(max_length=10)),
                ('MotivoConsultaCita', models.CharField(max_length=15)),
                ('EspecialidadCita', models.CharField(max_length=50)),
                ('HorarioCita', models.DateTimeField()),
                ('CitaPagada', models.BooleanField(default=0)),
                ('Asistencia', models.BooleanField(default=0)),
                ('MedicoAsignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDeCitas.medico')),
                ('PacienteConCita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDeCitas.paciente')),
                ('ReporteSec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDeCitas.reportesecretaria')),
            ],
        ),
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreAcu', models.CharField(max_length=50)),
                ('TelefonoAcu', models.CharField(max_length=11)),
                ('ParentescoAcu', models.CharField(max_length=20)),
                ('Apadrinado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDeCitas.paciente')),
            ],
        ),
    ]
