# Generated by Django 3.1.2 on 2020-10-19 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeCitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreAcu', models.CharField(max_length=50)),
                ('TelefonoAcu', models.CharField(max_length=11)),
                ('ParentescoAcu', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModalidadCita', models.CharField(max_length=10)),
                ('MotivoConsultaCita', models.CharField(max_length=15)),
                ('EspecialidadCita', models.CharField(max_length=50)),
                ('HorarioCita', models.DateField()),
                ('CitaPagada', models.BooleanField(default=0)),
                ('Asistencia', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimerNombre', models.CharField(max_length=50)),
                ('SegundoNombre', models.CharField(max_length=50)),
                ('PrimerApellido', models.CharField(max_length=50)),
                ('SegundoApellido', models.CharField(max_length=50)),
                ('Usuario', models.CharField(max_length=50)),
                ('Contraseña', models.CharField(max_length=50)),
                ('DocumentoId', models.IntegerField(max_length=12)),
                ('TipoDocumento', models.CharField(max_length=50)),
                ('Edad', models.IntegerField(max_length=3)),
                ('CorreoElectronico', models.CharField(max_length=90)),
                ('HorarioLlegada', models.DateField()),
                ('HoraioSalida', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimerNombre', models.CharField(max_length=50)),
                ('SegundoNombre', models.CharField(max_length=50)),
                ('PrimerApellido', models.CharField(max_length=50)),
                ('SegundoApellido', models.CharField(max_length=50)),
                ('Usuario', models.CharField(max_length=50)),
                ('Contraseña', models.CharField(max_length=50)),
                ('DocumentoId', models.IntegerField(max_length=12)),
                ('TipoDocumento', models.CharField(max_length=50)),
                ('Edad', models.IntegerField(max_length=3)),
                ('CorreoElectronico', models.CharField(max_length=90)),
                ('EPSP', models.CharField(max_length=90)),
                ('Telefono', models.CharField(max_length=20)),
                ('Whatsapp', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteSecretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaReporte', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimerNombre', models.CharField(max_length=50)),
                ('SegundoNombre', models.CharField(max_length=50)),
                ('PrimerApellido', models.CharField(max_length=50)),
                ('SegundoApellido', models.CharField(max_length=50)),
                ('Usuario', models.CharField(max_length=50)),
                ('Contraseña', models.CharField(max_length=50)),
                ('DocumentoId', models.IntegerField(max_length=12)),
                ('TipoDocumento', models.CharField(max_length=50)),
                ('Edad', models.IntegerField(max_length=3)),
                ('CorreoElectronico', models.CharField(max_length=90)),
                ('Whatsapp', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Prueba',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='Prueba',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='Prueba2',
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='DepartamentoC',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='NombreC',
            field=models.CharField(max_length=70),
        ),
        migrations.AddField(
            model_name='cita',
            name='MedicoAsignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDeCitas.medico'),
        ),
        migrations.AddField(
            model_name='cita',
            name='PacienteConCita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDeCitas.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='ReporteSec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDeCitas.reportesecretaria'),
        ),
        migrations.AddField(
            model_name='acudiente',
            name='Apadrinado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDeCitas.paciente'),
        ),
    ]
