# Generated by Django 3.1.2 on 2020-10-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeCitas', '0002_auto_20201018_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='TipoUsuario',
            field=models.CharField(default='Usuario', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='TipoUsuario',
            field=models.CharField(default='Usuario', max_length=20),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='TipoUsuario',
            field=models.CharField(default='Usuario', max_length=20),
        ),
        migrations.AlterField(
            model_name='medico',
            name='DocumentoId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medico',
            name='Edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='DocumentoId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='DocumentoId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='Edad',
            field=models.IntegerField(),
        ),
    ]
