# Generated by Django 3.1.2 on 2020-10-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeCitas', '0003_auto_20201018_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Diabetes',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Hipertension',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='paciente',
            name='PCardiacos',
            field=models.BooleanField(default=0),
        ),
    ]
