# Generated by Django 3.1.2 on 2020-10-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeCitas', '0004_auto_20201020_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='PCardiacos',
            new_name='Cardiacos',
        ),
        migrations.AddField(
            model_name='paciente',
            name='Barrio',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Ciudad',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Otros',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='paciente',
            name='complemento',
            field=models.CharField(default='', max_length=50),
        ),
    ]
