# Generated by Django 3.1.2 on 2020-10-30 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeCitas', '0004_auto_20201028_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='DiaCita',
            field=models.DateField(default=datetime.datetime(2020, 10, 30, 5, 2, 1, 105688, tzinfo=utc)),
        ),
    ]
