# Generated by Django 3.1.2 on 2020-10-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeCitas', '0005_auto_20201020_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='Especialidad',
            field=models.CharField(default='General', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='HorarioCita',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='medico',
            name='HoraioSalida',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='medico',
            name='HorarioLlegada',
            field=models.TimeField(),
        ),
    ]
