# Generated by Django 3.1.2 on 2020-11-08 07:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeCitas', '0005_auto_20201030_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='NecesitaReagendar',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='cita',
            name='DiaCita',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 7, 9, 39, 809260, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cita',
            name='MotivoConsultaCita',
            field=models.CharField(max_length=80),
        ),
    ]
