# Generated by Django 3.1.2 on 2020-11-08 22:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeCitas', '0006_auto_20201108_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='DiaCita',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 22, 53, 27, 826590, tzinfo=utc)),
        ),
    ]
