# Generated by Django 3.1.2 on 2020-11-17 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeCitas', '0007_auto_20201108_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='DiaCita',
            field=models.DateField(default=datetime.date(2020, 11, 17)),
        ),
    ]
